version: "3.8"
services:
  order-mysql:
    container_name: mysql
    image: mysql
    volumes:
      # UTF-8 인코딩 설정
      - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=order_db
      - MYSQL_USER=order
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=admin1234
      - TZ=Asia/Seoul
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci